- name: List project files
        working-directory: ./project
        run: ls -la
        
      - name: Show gradle-wrapper.properties
        working-directory: ./project
        run: cat gradle/wrapper/gradle-wrapper.properties
        
      - name: Show app/build.gradle
        working-directory: ./project
        run: cat app/build.gradle
